---
- name: Ensure helm repo is discarded
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "{{ helm_chart_url }}"
    repo_state: absent

- name: Ensure k8s-python package is discarded
  ansible.builtin.shell: |
    pip3 uninstall kubernetes --user
  ignore_errors: true

- name: Discard redis
  kubernetes.core.helm:
    name: "{{ release_name }}"
    chart_ref: bitnami/redis
    release_state: absent
    release_namespace: "{{ release_namespace }}"
    wait: true

- name: Discard namespace
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ release_name }}"
