---
- name: Check installation
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ release_namespace }}"
    field_selectors:
      - status.phase=Running
  register: results

- name: Report status
  debug:
    msg: "{{ results['msg']['api_found'] }}"
